### ISSUE TITLE
cannot add a new setting

### ISSUE THREAD

**Issue by undergroundtheater** [wastevens/ElysiumFrontend#7]
CRUD for "settings".  if not in the database, we should work towards that as 0.2 or 0.3, post-release.

**Comment by undergroundtheater** [comment]
by setting I mean GAME setting, such as "Sabbat", "Camarilla", "Anarch", "Camarilla-Anarch", etc.

**Comment by wastevens** [comment]
So, there's a few concepts at work here;
SETTING, I believe, needs to be a concept which lives in the code.  It ties into a variety of concepts that the rules enforcing piece will need to understand, often without a lot of coherence between the ideas.  Merit availability, Common/Uncommon/Rare clans, Setting alteration to default bloodline rarities, path discounts, generation caps tied to merits- there's a lot going on.  Setting is Camarilla, Sabbat, and Anarch.

VENUE is the collection of settings which cohere together as a shared universe within the UT.  These can be pulled from the database.  *Presently* they're in the code, because it was easier for me, but there's nothing about Venue that suggests the kind of complexity that lives in Setting.  By Venue, I currently mean 'Camarilla-Anarch-IA' and 'Sabbat'

GAME VENUE is the venue that a particular troupe is in.  Troupes will exist within one and only one of the shared setting universes.

GAME SETTING is the setting or settings within the Game Venue that a particular troupe allows characters from.

Moving Venue to the database, as mentioned, shouldn't be that bad, but seems relatively lower priority to me.

**Comment by undergroundtheater** [comment]
That's fine - if you could create milestones for the project and move this one to a later milestone, we still want to track this.  We need to be able to add a new "game setting"; it's okay if "setting" is hard-coded, but realize we have a strange "setting" compilation.  we have the custom one ("cam-anarch-IA") and a standard one ("sabbat").  At some point, we'll want to be able to create a "camarilla" game setting, and an "anarch" game setting, etc.  If this means we hard-code camarilla, anarch, IA (does not exist in the book), the "custom" triple threat, and sabbat that's fine, too.

In the end, as-is is fine, as long as a future update to add more doesn't break the database. :)

**Comment by wastevens** [comment]
Created as a milestone.  Closed as an issue.
